#---------------------
# Matthew Robillard
#-----------------------------------

all: install-all

install-all:
	cp .git-completion.bash /usr/local/bin/
        cp .git-prompt.sh /usr/local/bin/
	cp .bash_profile ~/
	source ~/.bash_profile 
	
